name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create Android project structure
      run: |
        mkdir -p android/app/src/main/assets
        mkdir -p android/app/src/main/java/com/chembyrika/app
        mkdir -p android/app/src/main/res/drawable
        mkdir -p android/app/src/main/res/values
        mkdir -p android/app/src/main/res/layout
        
    - name: Copy web assets
      run: |
        cp -r * android/app/src/main/assets/
        # Remove unnecessary files from assets
        rm -rf android/app/src/main/assets/android
        rm -rf android/app/src/main/assets/.github
        rm -rf android/app/src/main/assets/README
        rm -f android/app/src/main/assets/*.md
        
    - name: Create Android manifest
      run: |
        cat > android/app/src/main/AndroidManifest.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.chembyrika.app">
            
            <uses-permission android:name="android.permission.INTERNET" />
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
            
            <application
                android:allowBackup="true"
                android:icon="@drawable/ic_launcher"
                android:label="@string/app_name"
                android:theme="@style/AppTheme">
                
                <activity
                    android:name=".MainActivity"
                    android:exported="true"
                    android:configChanges="orientation|keyboardHidden|screenSize">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOF
        
    - name: Create MainActivity
      run: |
        cat > android/app/src/main/java/com/chembyrika/app/MainActivity.java << 'EOF'
        package com.chembyrika.app;
        
        import android.app.Activity;
        import android.os.Bundle;
        import android.webkit.WebView;
        import android.webkit.WebViewClient;
        import android.webkit.WebSettings;
        
        public class MainActivity extends Activity {
            private WebView webView;
            
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                
                webView = new WebView(this);
                setContentView(webView);
                
                WebSettings webSettings = webView.getSettings();
                webSettings.setJavaScriptEnabled(true);
                webSettings.setDomStorageEnabled(true);
                webSettings.setAllowFileAccess(true);
                webSettings.setAllowContentAccess(true);
                webSettings.setLoadWithOverviewMode(true);
                webSettings.setUseWideViewPort(true);
                webSettings.setBuiltInZoomControls(true);
                webSettings.setDisplayZoomControls(false);
                
                webView.setWebViewClient(new WebViewClient() {
                    @Override
                    public boolean shouldOverrideUrlLoading(WebView view, String url) {
                        view.loadUrl(url);
                        return true;
                    }
                });
                
                webView.loadUrl("file:///android_asset/index.html");
            }
            
            @Override
            public void onBackPressed() {
                if (webView.canGoBack()) {
                    webView.goBack();
                } else {
                    super.onBackPressed();
                }
            }
        }
        EOF
        
    - name: Create app icon
      run: |
        # Copy favicon.ico to Android drawable resources
        cp favicon.ico android/app/src/main/res/drawable/ic_launcher.png
        cp favicon.ico android/app/src/main/res/drawable/ic_launcher_round.png
        
        # Create adaptive icon using favicon
        cat > android/app/src/main/res/drawable/ic_launcher.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
            <background android:drawable="@color/ic_launcher_background"/>
            <foreground android:drawable="@drawable/ic_launcher"/>
        </adaptive-icon>
        EOF
        
    - name: Create colors
      run: |
        cat > android/app/src/main/res/values/colors.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <color name="ic_launcher_background">#2aabd2</color>
        </resources>
        EOF
        
    - name: Create strings
      run: |
        cat > android/app/src/main/res/values/strings.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <string name="app_name">Chem by Rika</string>
        </resources>
        EOF
        
    - name: Create styles
      run: |
        cat > android/app/src/main/res/values/styles.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <style name="AppTheme" parent="android:Theme.Material.Light.NoActionBar">
                <item name="android:colorPrimary">#2aabd2</item>
                <item name="android:colorPrimaryDark">#1a8bb2</item>
                <item name="android:colorAccent">#2aabd2</item>
            </style>
        </resources>
        EOF
        
    - name: Create build.gradle
      run: |
        cat > android/build.gradle << 'EOF'
        buildscript {
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:8.1.0'
            }
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        EOF
        
        cat > android/app/build.gradle << 'EOF'
        plugins {
            id 'com.android.application'
        }
        
        android {
            namespace 'com.chembyrika.app'
            compileSdk 34
            
            defaultConfig {
                applicationId "com.chembyrika.app"
                minSdk 21
                targetSdk 34
                versionCode 1
                versionName "1.0"
            }
            
            buildTypes {
                release {
                    minifyEnabled false
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                }
            }
            
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
        }
        
        dependencies {
            implementation 'androidx.appcompat:appcompat:1.6.1'
        }
        EOF
        
        cat > android/settings.gradle << 'EOF'
        include ':app'
        EOF
        
        cat > android/gradle.properties << 'EOF'
        org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
        android.useAndroidX=true
        android.enableJetifier=true
        EOF
        
    - name: Create gradle wrapper
      run: |
        cd android
        gradle wrapper
        
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: chembyrika-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Create Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: android/app/build/outputs/apk/release/app-release.apk
        tag_name: ${{ github.event.release.tag_name }}
        name: ChemByRika Android App
        body: |
          ChemByRika Android Application
          
          Built from commit: ${{ github.sha }}
          
          ## Installation
          Download and install the APK file on your Android device.
          
          ## Features
          - Offline chemistry synthesis routes
          - Search functionality
          - Responsive design for different screen sizes
