name: Build Capacitor APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Capacitor
      run: npm install -g @capacitor/cli

    - name: Initialize Capacitor project
      run: |
        if [ ! -f package.json ]; then
          npm init -y
        fi
        npm install @capacitor/core @capacitor/android
        npx cap init "Chem by Rika" com.chembyrika.app --web-dir=www

    - name: Copy web assets
      run: |
        mkdir -p www
        rsync -av --exclude 'android' --exclude 'www' ./ ./www/

    - name: Add Android platform
      run: npx cap add android

    - name: Sync web assets to Android
      run: npx cap copy android

    - name: Force Gradle 8.2.1 for Capacitor Android
      run: |
        echo "distributionUrl=https://services.gradle.org/distributions/gradle-8.2.1-bin.zip" > android/gradle/wrapper/gradle-wrapper.properties

    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: chembyrika-capacitor-apk
        path: android/app/build/outputs/apk/release/app-release.apk
