name: Build Cordova APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova project
      run: |
        cordova create app com.chembyrika.app "Chem by Rika"
        cd app
        cordova platform add android@12.0.0

    - name: Copy web assets
      run: |
        rsync -av --exclude 'app' --exclude '.github' --exclude '*.md' ./ ./app/www/

    - name: Convert favicon.ico to icon.png
      run: |
        sudo apt-get update && sudo apt-get install -y imagemagick
        convert favicon.ico -resize 192x192 app/www/icon.png

    - name: Set Cordova icon in config.xml
      run: |
        sed -i '/<platform name="android">/a \    <icon src="www/icon.png" />' app/config.xml

    - name: Force Gradle 8.2.1 for Cordova Android
      run: |
        cd app
        ls platforms/android/gradle/wrapper
        echo "distributionUrl=https://services.gradle.org/distributions/gradle-8.2.1-bin.zip" > platforms/android/gradle/wrapper/gradle-wrapper.properties

    - name: Build APK
      run: |
        cd app/platforms/android
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: chembyrika-cordova-apk
        path: app/platforms/android/app/build/outputs/apk/release/app-release.apk
